apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: python-app-11407
spec:
  type: NodePort
  selector:
    app: myapp-demo
  ports:
    - port: 8080
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
